server:
  port: ${PORT:3000}

logging:
  level:
    javax.jmdns: WARN

berry-control-hub:
  plugin-path: ${BCH_PLUGIN_PATH}

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:${BCH_DB_FILEPATH}
    username: sa
    password:
    driverClassName: org.h2.Driver
